defaults:
  - hydra/job_logging: disabled
  - hydra/output_subdir: null
hydra:
  output_subdir: null
  run:
    dir: logs/hydra
main:
  experiment_name_prefix: my_exp
  seed: 11
  num_workers: 8
  parallel: True
  gpus_to_use: 0,1,2
  trains: False
  paths:
    train: 'data/cache/train_target.pkl'
    validation: 'data/cache/val_target.pkl'
    logs: 'logs/'
    train_images_dir: '/datashare/train2014'
    val_images_dir: '/datashare/val2014'
train:
  num_epochs: 15
  grad_clip: 0.25
  dropout: 0.5
  num_hid: 1250
  batch_size: 128
  save_model: True
  lr:
    lr_value: 1e-3
    lr_decay: 30
    lr_gamma: 0.1
    lr_step_size: 30